name: Build
run-name: Building the mod...

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Version Title"
        required: true
      type:
        type: choice
        description: "Release Type"
        options:
        - release
        - beta
        - alpha
        required: false
        default: "release"
      changelog:
        description: "Changelog"
        required: false
        default: ""
      assets:
        type: boolean
        description: "Generate assets"
        required: false
        default: false
      publish:
        type: boolean
        description: "Publish to curseforge and modrinth"
        required: false
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "\nversion=${{ github.event.inputs.version }}" >> gradle.properties
      
      - run: rm -rf src/generated
        if: github.event.inputs.assets == 'true'
      - run: ./gradlew runData
        if: github.event.inputs.assets == 'true'
        continue-on-error: true
      - run: ./gradlew build
      
      - run: echo "FILE=$(ls -d build/libs/*)" >> $GITHUB_ENV
      - run: echo "FILENAME=$(cd build/libs; ls *)" >> $GITHUB_ENV
      - run: cd ../../

      - uses: Kir-Antipov/mc-publish@v3.3
        if: github.event.inputs.publish == 'true'
        with:
          name: ${{ env.FILENAME }}
          version: ${{ github.event.inputs.version }}
          version-type: ${{ github.event.inputs.type }}
          changelog: ${{ github.event.inputs.changelog }}
          loaders: "forge"
          game-versions: "1.16.5"
          java: "8"

          modrinth-id: "Lddihzs4"
          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}

          curseforge-id: 813035
          curseforge-token: ${{ secrets.CF_API_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${{ github.event.inputs.version }}