name: Build
run-name: Building the mod...

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Version Title"
        required: true
      type:
        type: choice
        description: "Release Type"
        options:
        - release
        - beta
        - alpha
        required: false
        default: "release"
      changelog:
        description: "Changelog"
        required: false
        default: ""
      publish:
        type: boolean
        description: "Publish to curseforge and modrinth"
        required: false
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "version=${{ github.event.inputs.version }}" >> gradle.properties
      - run: ./gradlew build
      - run: echo "FILE=$(ls -d build/libs/*)" >> $GITHUB_ENV
      - run: echo "FILENAME=$(cd build/libs; ls *)" >> $GITHUB_ENV
      - run: cd ../../

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
        id: create_release

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.FILE }}
          asset_name: ${{ env.FILENAME }}
          asset_content_type: application/java-archive
          
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}

      - uses: itsmeow/curseforge-upload@v3
        if: github.event.inputs.publish == 'true'
        with:
          file_path: ${{ env.FILE }}
          game_endpoint: "minecraft"
          game_versions: "Minecraft 1.16:1.16.5,Java 8,Forge,Client,Server"
          release_type: ${{ github.event.inputs.type }}
          changelog: ${{ github.event.inputs.changelog }}
          project_id: "813035"
          token: ${{ secrets.CF_API_TOKEN }}